name: Test cache
on:
  workflow_dispatch:
  push:
    branches:
      - master
  
jobs:
  chache:
    runs-on: ubuntu-latest
    steps:
      - name: Cache runtime log
        uses: actions/cache@v3
        with:
          path: |
            tmp/parallel_runtime_rspec.log
          key: parallel-runtime-log
          restore-keys: parallel-runtime-log
          
      - name: Get commit sha
        shell: bash
        run: echo "SHORT_SHA=$(echo -n ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
       
      - name: Create file
        run: |
          mkdir -p tmp
          echo "master-${{ env.SHORT_SHA }}" > tmp/parallel_runtime_rspec.log
         
      - name: Show file
        run: cat tmp/parallel_runtime_rspec.log
          
