name: Test call 

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        type: string
        required: false
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

env:
  TAG: ${{ inputs.tag || github.ref_name == 'main' && github.sha || github.ref_name }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        run: echo $TAG
