name: Deploy

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/cache@v3
      with:
        path: |
          tmp/parallel_runtime_rspec.log
        key: runtime
      
    - run: cat tmp/parallel_runtime_rspec.log
    
  cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v3
      with:
        path: |
          tmp/parallel_runtime_rspec.log
        key: runtime
        
    - run: cat tmp/parallel_runtime_rspec.log


    
      
