name: Deploy

on:
  workflow_dispatch:
    inputs:
     DEPLOY_TYPE:
     ACTOR:
      default: ${{ github.actor }}

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: User
      run: echo ${{ github.event.inputs.ACTOR }}
