name: Reusable workflow

on:
  workflow_dispatch:
    inputs:
      time:
        type: string
        default: 1m
  workflow_call:
    inputs:
      time:
        type: string
        default: 1m

jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: sleep ${{ inputs.time }}
