name: Env

on:
  workflow_run:
    workflows: [Fail status]
    types:
      - completed

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Install
      run: echo "start"
        
    
  
