name: Env

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: event
        run: cat $GITHUB_EVENT_PATH
      - name: anotation
        uses: mholetzko/annotate_runs@v1.0.0
        with:
          title: 'Example Annotation Title\n dawdawd'
          info: 'This is an info'
          warning: 'This is a warning'
          
        
        
    
  
