name: Re-run failed tests

on:
  workflow_run:
    workflows:
      - Fail status
    types:
      - completed

jobs:
  re-run:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: [self-hosted, main]
    steps:
      - name: Re-run failed tests
        run: echo "Re-run"

          
        
        
    
  
