name: Re-run failed tests

on:
  workflow_run:
    workflows:
      - Fail status
    types:
      - completed

jobs:
  re-run:
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.run_attempt < 3 }}
    runs-on: ubuntu-latest
    steps:
      - name: Re-run failed tests
        run: echo "Attempt ${{ github.event.workflow_run.run_attempt }}"

          
        
        
    
  
