name: Env

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "STATUS=$(curl -s "https://api.github.com/repos/hiering/test/actions/workflows/fail-status.yml/runs" | jq -r '.workflow_runs[0].status')" >> $GITHUB_ENV
      - run: echo $STATUS 
  
  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
      - name: Print status
        run: echo status=${{ env.STATUS }}
    
  
