name: Test

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get
        run: echo TAG
  job2:
    uses: ./.github/workflows/re-useble.yml
    with:
      time: 1m
