name: Test

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Succesed step
        run: echo 0
        
      - name: Failed step
        run: bash -c "exit 1"
        
      - name: Succesed step
        run: echo 0

