name: Test

on:
  workflow_dispatch:
    inputs:
      deploy-type:
        description: DEPLOY TYPE
        default: ruby-rakes ruby-sidekiq ruby-unicorn-www ruby-daemons ruby-unicorn-api ruby-prometheus-exporter
        type: string
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo test=$(echo '"${{ inputs.deploy-type }}"' | jq 'split(" ")' >> $GITHUB_OUTPUT
        
  job2:
    runs-on: ubuntu-latest
    needs: job1
    strategy:
      fail-fast: false
      matrix:
        language: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.language}}


    
      
