name: Test

on:
  workflow_dispatch:
  push:

jobs: 
  cache:
    runs-on: ubuntu-latest
    steps:
    - name: Cache runtime log
      uses: actions/cache@v3
      with:
          path: |
            tmp/parallel_runtime_rspec.log
          key: parallel-runtime-log
          restore-keys: parallel-runtime-log
        
    - run: cat tmp/parallel_runtime_rspec.log


    
      
